CREATE DATABASE IF NOT EXISTS db;
USE db;
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
    token varchar(64) NOT NULL PRIMARY KEY,
    account_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS donations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    coins BIGINT UNSIGNED NOT NULL,
    donated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    income_eur DOUBLE NOT NULL,
    co_op ENUM('S4L','STUDIO-MATIC') NOT NULL
);
CREATE TABLE IF NOT EXISTS supporters (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT "Anonymous",
    donation_id BIGINT UNSIGNED NOT NULL UNIQUE,
    FOREIGN KEY (donation_id) REFERENCES donations(id) ON DELETE CASCADE ON UPDATE CASCADE
);
